In [ ]:
import tensorflow as tf

In [ ]:
tf_string = tf.constant('Hello', dtype=tf.string)
tf_num = tf.constant(242552.2425324, dtype=tf.float64)

In [ ]:
tf_string, tf_num

(<tf.Tensor: shape=(), dtype=string, numpy=b'Hello'>,
 <tf.Tensor: shape=(), dtype=float64, numpy=242552.2425324>)

In [ ]:
tf.rank(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
tf.rank(tf_string).shape

TensorShape([])

In [ ]:
tf_mat = tf.constant([[13, 13, 3], [213.123, 523.453, 14.12131]], dtype=tf.float64)

In [ ]:

tf.rank?

In [ ]:
tf_mat.shape

TensorShape([2, 3])

In [ ]:
assert isinstance(tf_mat, tf.Tensor), "matrix must be a tf Tensor object"
assert tf.rank(tf_mat).numpy() == 2

In [ ]:
# 4 D tensor, of shape (10, 256, 256, 3)
# Similar to 10 RGB images of 256 * 256 pixels

images = tf.zeros(shape=(10, 256, 256, 3), dtype=tf.uint16)

In [ ]:
assert isinstance(images, tf.Tensor), "matrix must be a tf Tensor object"
assert tf.rank(images).numpy() == 4, "matrix must be of rank 4"
assert tf.shape(images).numpy().tolist() == [10, 256, 256, 3], "matrix is incorrect shape"

In [ ]:
tf.shape(images).numpy()

array([ 10, 256, 256,   3], dtype=int32)

In [ ]:
tf.rank(images)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

## Computation on Tensors

In [ ]:
a = tf.constant(123)
b = tf.constant(22)

In [ ]:
a + b

<tf.Tensor: shape=(), dtype=int32, numpy=145>

In [ ]:
tf.add(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=145>

In [ ]:

tf.divide?

In [ ]:


### Defining Tensor computations ###

# Construct a simple computation function
def func(a,b):
  '''TODO: Define the operation for c, d, e (use tf.add, tf.subtract, tf.multiply).'''
  c = tf.add(a, b)
  d = tf.subtract(a, b)
  e = tf.multiply(a, b)
  return e



In [ ]:
# Consider example values for a,b
a, b = 1.5, 2.5
# Execute the computation
e_out = func(a,b)
print(e_out)

tf.Tensor(3.75, shape=(), dtype=float32)


<img url=https://camo.githubusercontent.com/273c1d7e82c4ced2b3567fe92adf1b3db4836cc0cdd9e3b094486136b6d520eb/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f61616d696e692f696e74726f746f646565706c6561726e696e672f6d61737465722f6c6162312f696d672f636f6d7075746174696f6e2d67726170682d322e706e67>